import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, Clock3, MapPin, ShieldCheck } from "lucide-react";
import "./careers.css";

const openings = [
  { title: "Senior Cybersecurity Analyst", team: "Security Operations", type: "Full-time", location: "RBS Accelerator, 4th Floor, 110 Queen St, Glasgow G1 3BX", posted: "2 days ago", summary: "Lead our Security Operations Center in monitoring, detecting and responding to advanced cybersecurity threats across our global client base.", requirements: ["Bachelor's degree in Cybersecurity, Computer Science, or related field", "5+ years experience in SOC operations and incident response", "CISSP, GCIH, or GCFA certification required"], more: "+9 more requirements" },
  { title: "Fractional CFO", team: "Finance", type: "Part-time", location: "Online", posted: "3 days ago", summary: "Provide strategic financial leadership on a part-time basis, overseeing planning, analysis and reporting to drive sustainable business growth.", requirements: ["Master's degree in Finance, Accounting, or MBA preferred", "10+ years experience in financial leadership roles", "CPA or CFA certification preferred"], more: "+3 more requirements" },
  { title: "Business Development Head", team: "Business Development", type: "Full-time", location: "RBS Accelerator, 4th Floor, 110 Queen St, Glasgow G1 3BX", posted: "1 week ago", summary: "Lead growth initiatives by building strategic partnerships, managing key relationships and expanding our cybersecurity service offerings.", requirements: ["Bachelor's degree in Business, Marketing, or related field", "5+ years experience in B2B sales, preferably in cybersecurity", "Proven track record of meeting and exceeding sales targets"], more: "+3 more requirements" },
  { title: "Cybersecurity Intern", team: "Security Operations", type: "Internship", location: "RBS Accelerator, 4th Floor, 110 Queen St, Glasgow G1 3BX", posted: "1 week ago", summary: "Gain hands-on experience in cybersecurity operations, threat analysis and security research in a dynamic learning environment.", requirements: ["Currently pursuing a Cybersecurity, Computer Science, or related degree", "Basic understanding of networking and security concepts", "Familiarity with Linux and Windows operating systems"], more: "+3 more requirements" },
];

export default function CareersPage() { return <main className="careers-page"><header className="careers-nav"><Link href="/" className="careers-brand"><img src="/cyberthistle-shield.png" alt="CyberThistle shield"/><span>CYBER THISTLE<small>SECURE SOLUTIONS · SEAMLESS EXPERIENCES</small></span></Link><Link href="/" className="careers-home">Back to home <ArrowRight size={15}/></Link></header><section className="careers-hero"><p>CAREERS / CYBER THISTLE</p><h1>Build security<br/><em>that outlasts</em> the threat.</h1><div><span><ShieldCheck size={17}/> High-impact work</span><span><ShieldCheck size={17}/> Expert-led teams</span><span><ShieldCheck size={17}/> Glasgow + remote</span></div></section><section className="openings"><div className="openings-heading"><div><p>OPEN ROLES</p><h2>Current openings</h2></div><b><span>04</span> Positions available</b></div><div className="opening-list">{openings.map((job,index)=><article className="opening" key={job.title}><div className="opening-number">0{index+1}</div><div className="opening-main"><div className="opening-title"><div><p>{job.team}</p><h3>{job.title}</h3></div><time><Clock3 size={14}/>{job.posted}</time></div><div className="opening-meta"><span><BriefcaseBusiness size={15}/>{job.type}</span><span><MapPin size={15}/>{job.location}</span></div><p className="opening-summary">{job.summary}</p><div className="requirements"><b>Key requirements</b><ul>{job.requirements.map(item=><li key={item}>{item}</li>)}</ul><small>{job.more}</small></div></div><div className="opening-actions"><a href="#apply">View details <ArrowRight size={15}/></a><a href="mailto:careers@cyberthistle.com?subject=Application%20for%20CyberThistle" className="apply">Quick apply <ArrowRight size={15}/></a></div></article>)}</div></section><section className="careers-cta" id="apply"><p>DON’T SEE YOUR ROLE?</p><h2>Bring your edge.<br/><em>We’ll build the rest.</em></h2><p>Send us your profile and tell us how you want to shape the next security standard.</p><a href="mailto:careers@cyberthistle.com">Introduce yourself <ArrowRight size={17}/></a></section></main>; }
